### PR TITLE
:bug: Update for Gnome 3.32

### PR DESCRIPTION
**Pull request by Striffly**
The icon is missing, but everything else works.
If someone know how to fix the icon please do a PR on my fork ! :)

### CODE REVIEW

**Comment by eode** [comment]
Can confirm that this works, mostly, but needs the following:

* Icon (as @Striffly mentioned)
* Completely remove when turned off (prevents turning back on again)
* Don't crash if no folder is set

**Comment by eode** [comment]
..took a stab at the icon issue, but ran out of time.  :-(

**Comment by rugk** [comment]
Maybe add "Fixes https://github.com/rodakorn/randwall/issues/41".

**Review by frnogueira — APPROVED** [review]

**Comment by Striffly** [comment]
> Can confirm that this works, mostly, but needs the following:
> 
>     * Icon (as @Striffly mentioned)
> 
>     * Completely remove when turned off (prevents turning back on again)
> 
>     * Don't crash if no folder is set

@rodakorn don't forget this please ! :)

**Pull request merged**
